<?php
ini_set("display_errors",1);
error_reporting(E_ALL);

# This file was automatically generated by the MediaWiki 1.22.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "GO Wiki";
$wgMetaNamespace = "GO_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost:8080";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogo             = "$wgStylePath/common/images/wiki.png";
$wgLogo              = "$wgStylePath/common/images/go.png";
#$wgLogo              = "$wgStylePath/common/images/GO-s.png";  # too big?

## The relative URL and path to the upload directory
$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";

## UPO means: this is also a user preference option
$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO
$wgEmailConfirmToEdit = false;  # requries email address when registering

$wgEmergencyContact = "sysadmin@changme.edu";
$wgPasswordSender = "sysadmin@changeme.edu";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki";
$wgDBuser = "root";
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageResize      = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# This is the list of preferred extensions for uploading files. Uploading files
#with extensions not in this list will trigger a warning.
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'ppt', 'pdf', 'doc', 'xls', 'csv', 'tsv', 'docx', 'xlsx', 'pptx', 'txt', 'psd' );

# Max size for uploads, in bytes 
# Currently has no effect, must update /etc/php.ini (upload_max_filesize and post_max_size)
$wgMaxUploadSize = 1024*1024*100; # 100MB = default

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
#$wgShellLocale = "en_US.utf8";
$wgShellLocale = "en_CA.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache";

# invalidates all cached pages whenever LocalSettings.php is changed
$wgInvalidateCacheOnLocalSettingsChange = true;

# activate server-side file caching for non-logged-in users to reduce database traffic
$wgUseFileCache = false; /* default: false */
$wgFileCacheDirectory = "$IP/cache";
$wgShowIPinHeader = false;

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "5555555555555555555555555555555555555555555555555555555555555555";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "888888888888888";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'cologneblue', 'monobook', 'vector':
## AES: $wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

# Vampire account creation
# prevent user account creation - From Jim Hu  and Dan Renfro
$wgGroupPermissions['*']['createaccount'] = false; // prevent any account creation
$wgGroupPermissions['*']['read']         = true;   // 1.5.0 anyone can read without login
$wgGroupPermissions['*']['edit']         = false;  // 1.5.0 blocks editing without login
$wgGroupPermissions['*']['createpage']   = false;  // 1.6.0 
$wgGroupPermissions['*']['createtalk']   = false;  // 1.6.0

# vampire-model enforcing - from Jim Hu and Dan Renfro 
$wgGroupPermissions['user']['createaccount'] = true;  // another user can create account

# Specifies the minimal length of a user password. 
# If set to 0, empty passwords are allowed.
$wgMinimalPasswordLength = 6;

# Treat language links as magic connectors, not inline links = Default
$wgInterwikiMagic = true;

# Change $wgRCMaxAge from 13 weeks -> 2 week
#$wgRCMaxAge = 13 * 7 * 24 * 3600;
$wgRCMaxAge = 2 * 7 * 24 * 3600;

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
require_once "$IP/extensions/Cite/Cite.php";
require_once "$IP/extensions/LocalisationUpdate/LocalisationUpdate.php";
require_once "$IP/extensions/Nuke/Nuke.php";
require_once "$IP/extensions/ParserFunctions/ParserFunctions.php";  # collapsible lists
$wgPFEnableStringFunctions = true;
require_once "$IP/extensions/Renameuser/Renameuser.php";
require_once "$IP/extensions/SimpleAntiSpam/SimpleAntiSpam.php";
require_once "$IP/extensions/SpamBlacklist/SpamBlacklist.php";
require_once "$IP/extensions/WikiEditor/WikiEditor.php";
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;

## Install the following extensions manually

# Correct way to remove users from wiki
require_once( "$IP/extensions/UserMerge/UserMerge.php" );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

#require_once( "$IP/extensions/googleAnalytics/googleAnalytics.php" );
## Replace xxxxxxx-x with YOUR GoogleAnalytics UA number
#$wgGoogleAnalyticsAccount = "xxxxxxx-x";
## Optional Variables (both default to true)
#$wgGoogleAnalyticsIgnoreSysops = false;
#$wgGoogleAnalyticsIgnoreBots = false;
## If you use AdSense as well and have linked your accounts, set this to true to enable tracking
#$wgGoogleAnalyticsAddASAC = false;

# Extensions for GoWiki
include( "$IP/extensions/ProtectSection/ProtectSection.php" );
include( "$IP/extensions/iframe_embed.php" ); 
require_once( "$IP/extensions/Cite/Cite.php" );

require_once( "$IP/extensions/TableEdit/TableEdit.php" );
require_once( "$IP/extensions/TableEdit/modules/TableMarkerUpper.php" );

# Enforce addition of categories
require_once "$IP/extensions/AbuseFilter/AbuseFilter.php";
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['*']['abusefilter-log-detail'] = true;
$wgGroupPermissions['*']['abusefilter-view'] = true;
$wgGroupPermissions['*']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-private'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;

# Needs to be at the bottom of this file
require_once( "$IP/extensions/AntiSpoof/AntiSpoof.php" );
$wgSharedTables[] = 'spoofuser';

require_once "$IP/skins/Vector/Vector.php";
// mw.v 1.25.x or above
wfLoadSkin( 'Vector' );
?>
